---
layout: text
math: true
section: blog
title: Finite presentation basics
permalink: /finite-presentation-basics
desc: Two basic facts about finite presentation, proved for both
      modules and algebras at the same time!
---

We recall the definitions and prove two basic statements about finite
presentation, that "finitely presented implies always finitely
presented"[^always] and that it is a local property. The proofs in the
setting of modules and in the setting of algebras are completely
analogous, so we will abstract very slightly and address both at once.

Our notation is as follows:

- All rings and algebras are commutative with unit.
- For a ring $$A$$, let $$\mc{C}_A$$ denote either the category of
  $$A$$-modules or the category of $$A$$-algebras. All arrows indicate
  morphisms in $$\mc{C}_A$$.
- Let $$\amalg$$ denote the coproduct in $$\mc{C}_A$$, i.e., direct
  sum $$\oplus$$ for $$A$$-modules or tensor product $$\otimes_A$$ for
  $$A$$-algebras.
- For $$C \in \ob(\mc{C}_A)$$ and $$n \in \bb{N}$$ let $$C^{\amalg
  n}$$ denote the $$n$$-fold coproduct $$C \amalg \cdots \amalg C$$
  and $$C^n$$ denote the $$n$$-fold product $$C \times \cdots \times
  C$$.
- Let $$F_A \in \ob(\mc{C}_A)$$ denote the free object on one element,
  i.e., $$F_A \simeq A$$ for $$A$$-modules and $$F_A \simeq A[t]$$ for
  $$A$$-algebras. Thus for any $$n \in \bb{N}$$ there is an
  isomorphism $$\hom_{\mc{C}_A}(F_A^{\amalg n},C) \simeq C^n$$ natural
  in $$C \in \ob(\mc{C}_A)$$.

Now to the content. Fix a ring $$A$$ for the remainder.

**Definition.**
An object $$C \in \ob(\mc{C}_A)$$ is:

1. *finitely generated* if for some $$n \in \bb{N}$$ there is a
   surjection $$F_A^{\amalg n} \to M$$;
2. *finitely presented* if for some $$n \in \bb{N}$$ there is a
   surjection $$F_A^{\amalg n} \to M$$ with finitely generated
   kernel.

**Lemma.**
*Let $$f \c C \to D$$ and $$g \c D \to E$$ be morphisms in
$$\mc{C}_A$$.  Define $$h \ce g \circ f$$. Then if $$f$$ is
surjective, the canonical morphism $$\ker(h) \to \ker(g)$$ induced by
$$f$$ is surjective. In particular, if $$\ker(h)$$ is finitely
generated then so is $$\ker(g)$$.*

*Proof.*
Evident. $$\qed$$

**Proposition** (Finitely presented $$\Rightarrow$$ always finitely
  presented)**.**
*Let $$C \in \ob(\mc{C}_A)$$ be finitely presented. If $$\alpha \c D
\to C$$ is a surjection with $$D$$ finitely generated, then
$$\ker(\alpha)$$ is finitely generated.*

*Proof.*
By the previous lemma we may assume $$D \simeq F_A^{\amalg m}$$. By
definition we have a surjection $$\beta \c F_A^{\amalg n} \to C$$ with
$$\ker(\beta)$$ finitely generated. Consider the diagram

$$
\begin{xy}
\xymatrix {
 & F_A^{\amalg m} \ar@{>>}[dr]^\alpha & \\
 F_A^{\amalg m} \amalg F_A^{\amalg n}
 \ar@{>>}[ur]^{\id\,\amalg\,\xi}
 \ar@{>>}[dr]_{\eta\,\amalg\,\id}
 \ar@{>>}[rr]^-\gamma
 & & C, \\
 & F_A^{\amalg n} \ar@{>>}[ur]_\beta &
}
\end{xy}
$$

where $$\xi \c F_A^{\amalg n} \to F_A^{\amalg m}$$ and $$\eta \c
F_A^{\amalg m} \to F_A^{\amalg n}$$ are defined such that $$\alpha
\circ \xi = \beta$$ and $$\beta \circ \eta = \alpha$$---which exist
since free objects are projective in $$\ob(\mc{C}_A)$$---so that
defining $$\gamma \ce \alpha \amalg \beta$$ makes the diagram
commute. Now, if $$t_1,\ldots,t_m$$ are the canonical generators (in
the appropriate sense according to $$\mc{C}_A$$) of $$F_A^{\amalg
m}$$, then clearly $$\ker(\gamma)$$ is generated by $$\ker(\beta)$$
and $$\{t_i - \eta(t_i)\}_{1 \le i \le m}$$. Thus $$\ker(\beta)$$
being finitely generated implies $$\ker(\gamma)$$ is finitely
generated, which implies $$\ker(\alpha)$$ is finitely generated by the
previous lemma. $$\qed$$

**Proposition** (Finite generation and presentation are local)**.**
*Let $$C \in \ob(\mc{C}_A)$$.*

1. *If $$C$$ is finitely generated (resp. presented), then for any $$f
   \in A$$ the localisation $$C_f$$ is finitely generated
   (resp. presented) in $$\mc{C}_{A_f}$$.*
2. *If $$f_1,\ldots,f_n \in A$$ generate the unit ideal and
   $$C_{f_i}$$ is finitely generated (resp. presented) in
   $$\mc{C}_{A_{f_i}}$$ for each $$i$$, then $$C$$ is finitely
   generated (resp. presented).*

*Proof.*
We first address finite generation.

1. Observe $$(F_A)_f \simeq F_{A_f}$$. Thus, since localisation is
   exact (and hence commutes with finite products), a surjection
   $$F_A^{\amalg n} \to C$$ localises to a surjection
   $$F_{A_f}^{\amalg n} \to C_f$$.
2. Suppose $$C_{f_i}$$ is generated (in the appropriate sense) by
   $$\{a_{i,j}/f_i^{r_{i,j}}\}_{1 \le j \le m_i}$$ for each $$i$$.
   Take $$R \ge \max\{r_{i,j}\}$$. Then for all $$i$$ we have that
   $$f_i^Ra$$ is generated by $$\{a_{i,j}\}$$ for any $$a \in
   A$$. Since $$f_1,\ldots,f_n$$ generate the unit ideal, so do
   $$f_1^R,\ldots,f_n^R$$ and hence there exist $$c_i \in A$$ such
   that $$\sum c_if_i^R = 1$$. It is then clear that $$\{c_i\} \cup
   \{a_{i,j}\}$$ generates $$C$$.

Now finite presentation. Recall since localisation commutes with
kernels since it is exact.

1. This is immediate from localisation commuting with kernels and that
   we have proved (1) for finite generation.
2. Since we have proved (2) for finite generation there is a
   surjection $$\alpha \c F_A^{\amalg n} \to C$$. Then for each $$i$$,
   $$\alpha_{f_i} \c F_{A_{f_i}}^{\amalg n} \to C_{f_i}$$ is a
   surjection, so by the first proposition (finitely presented implies
   always finitely presented) we know $$\ker(\alpha_{f_i}) \simeq
   \ker(\alpha)_{f_i}$$ is finitely generated. By the statement (2)
   for finite generation this implies $$\ker(\alpha)$$ is finitely
   generated as desired. $$\qed$$

Ok that's it! I mostly wanted to write this up because you can prove
it in both settings at once, which I found fun. I thought a bit about
axiomiatising the type of category one could prove this for, but I
ended up wanting to assume a lot of stuff and it seemed like the
exposition would get pretty ugly.

**Remark.**
This last proposition is what one needs to prove when showing that a
morphism of schemes being of locally of finite type or locally of
finite presentation is local on the source.



[^always]:
    This catchy phrasing for the proposition is taken from [Vakil's
    notes][vakil].



[vakil]: //math216.wordpress.com/