---
layout: text
math: true
section: math
date: 2014-05-29 20:00:00 -0500
title: Finite presentation basics
permalink: /finite-presentation-basics
desc: Two basic facts about finite presentation, proved for both
      modules and algebras at the same time!
preamble:
- [c, 0, "\\colon"]
- [ce, 0, "\\mathrel{:=}"]
- [obj, 0, "\\opname{obj}"]
- [hom, 0, "\\opname{hom}"]
- [id, 0, "\\mathrm{id}"]
- [ker, 0, "\\opname{ker}"]
- [max, 0, "\\opname{max}"]
- [C, 0, "\\mathcal{C}"]
- [N, 0, "\\mathbf{N}"]
---

We recall the definitions and prove two basic statements about finite
presentation, that "finitely presented implies always finitely
presented"[^always] and that it is a local property. The proofs in the
setting of modules and in the setting of algebras are completely
analogous, so we will abstract very slightly and address both at once.

Our notation is as follows:

- All rings and algebras are commutative with unit.
- For a ring $A$, let $\C_A$ denote either the category of $A$-modules
  or the category of $A$-algebras. All arrows indicate morphisms in
  $\C_A$.
- Let $\amalg$ denote the coproduct in $\C_A$, i.e., direct sum
  $\oplus$ for $A$-modules or tensor product $\otimes_A$ for
  $A$-algebras.
- For $C \in \obj(\C_A)$ and $n \in \N$ let $C^{\amalg n}$ denote the
  $n$-fold coproduct $C \amalg \cdots \amalg C$ and $C^n$ denote the
  $n$-fold product $C \times \cdots \times C$.
- Let $F_A \in \obj(\C_A)$ denote the free object on one element,
  i.e., $F_A \iso A$ for $A$-modules and $F_A \iso A[t]$ for
  $A$-algebras. Thus for any $n \in \N$ there is an isomorphism
  $\hom_{\C_A}(F_A^{\amalg n},C) \iso C^n$ natural in $C \in
  \obj(\C_A)$.

Now to the content. Fix a ring $A$ for the remainder.

\begin{definition}
An object $C \in \obj(\C_A)$ is:

1. *finitely generated* if for some $n \in \N$ there is a surjection
   $F_A^{\amalg n} \to M$;
2. *finitely presented* if for some $n \in \N$ there is a surjection
   $F_A^{\amalg n} \to M$ with finitely generated kernel.

\end{definition}

\begin{lemma}{ker-surjection}
Let $f \c C \to D$ and $g \c D \to E$ be morphisms in $\C_A$.  Define
$h \ce g \circ f$. Then if $f$ is surjective, the canonical morphism
$\ker(h) \to \ker(g)$ induced by $f$ is surjective. In particular, if
$\ker(h)$ is finitely generated then so is $\ker(g)$.
\end{lemma}

\begin{proof}
Evident.
\end{proof}

Now the first fact: once finitely presented, always finitely
presented.

\begin{proposition}{fp-implies-always-fp}
Let $C \in \obj(\C_A)$ be finitely presented. If $\alpha \c D \to C$
is a surjection with $D$ finitely generated, then $\ker(\alpha)$ is
finitely generated.
\end{proposition}

\begin{proof}
By \ref{ker-surjection} we may assume $D \iso F_A^{\amalg m}$. By
definition we have a surjection $\beta \c F_A^{\amalg n} \to C$ with
$\ker(\beta)$ finitely generated. Consider the diagram
\[
\begin{xy}
\xymatrix {
 & F_A^{\amalg m} \ar@{>>}[dr]^\alpha & \\
 F_A^{\amalg m} \amalg F_A^{\amalg n}
 \ar@{>>}[ur]^{\id\,\amalg\,\xi}
 \ar@{>>}[dr]_{\eta\,\amalg\,\id}
 \ar@{>>}[rr]^-\gamma
 & & C, \\
 & F_A^{\amalg n} \ar@{>>}[ur]_\beta &
}
\end{xy}
\]
where $\xi \c F_A^{\amalg n} \to F_A^{\amalg m}$ and $\eta \c
F_A^{\amalg m} \to F_A^{\amalg n}$ are defined such that $\alpha \circ
\xi = \beta$ and $\beta \circ \eta = \alpha$---which exist since free
objects are projective in $\C_A$---so that defining $\gamma \ce \alpha
\amalg \beta$ makes the diagram commute. Now, if $t_1,\ldots,t_m$ are
the canonical generators (in the appropriate sense according to
$\C_A$) of $F_A^{\amalg m}$, then clearly $\ker(\gamma)$ is generated
by $\ker(\beta)$ and $\{t_i - \eta(t_i)\}_{1 \le i \le m}$. Thus
$\ker(\beta)$ being finitely generated implies $\ker(\gamma)$ is
finitely generated, which implies $\ker(\alpha)$ is finitely generated
by \ref{ker-surjection}.
\end{proof}

This in turn allows us to prove the second fact: finite generation and
presentation are local properties.

\begin{proposition}{fg-fp-local}
Let $C \in \obj(\C_A)$.

1. If $C$ is finitely generated (resp. presented), then for any $f \in
   A$ the localisation $C_f$ is finitely generated (resp. presented)
   in $\C_{A_f}$.
2. If $f_1,\ldots,f_n \in A$ generate the unit ideal and $C_{f_i}$ is
   finitely generated (resp. presented) in $\C_{A_{f_i}}$ for each
   $i$, then $C$ is finitely generated (resp. presented).
\end{proposition}

\begin{proof}
We first address finite generation.

1. Observe $(F_A)_f \iso F_{A_f}$. Thus, since localisation is exact
   (and hence commutes with finite products), a surjection
   $F_A^{\amalg n} \to C$ localises to a surjection $F_{A_f}^{\amalg
   n} \to C_f$.
2. Suppose for each $i$ that $C_{f_i}$ is generated (in the
   appropriate sense) by $\{a_{i,j}/f_i^{r_{i,j}}\}_{1 \le j \le
   m_i}$.  Take $R \ge \max\{r_{i,j}\}$. Then for all $i$ we have that
   $f_i^Ra$ is generated by $\{a_{i,j}\}$ for any $a \in A$. Since
   $f_1,\ldots,f_n$ generate the unit ideal, so do
   $f_1^R,\ldots,f_n^R$ and hence there exist $c_i \in A$ such that
   $\sum c_if_i^R = 1$. It is then clear that $\{c_i\} \cup
   \{a_{i,j}\}$ generates $C$.

Now finite presentation. Recall that localisation commutes with
kernels since it is exact.

1. This is immediate from localisation commuting with kernels and that
   we have proved (i) for finite generation.
2. Since we have proved (ii) for finite generation there is a
   surjection $\alpha \c F_A^{\amalg n} \to C$. Then for each $i$,
   \[
   \alpha_{f_i} \c F_{A_{f_i}}^{\amalg n} \to C_{f_i}
   \]
   is a surjection, so by \ref{fp-implies-always-fp} we know
   $\ker(\alpha_{f_i}) \iso \ker(\alpha)_{f_i}$ is finitely
   generated. By statement (ii) for finite generation this implies
   $\ker(\alpha)$ is finitely generated as desired.  \end{proof}

Ok that's it! I mostly wanted to write this up because you can prove
it in both settings at once, which I found fun. I thought a bit about
axiomiatising the type of category one could prove this for, but I
ended up wanting to assume a lot of stuff and it seemed like the
exposition would get pretty ugly.

\begin{remark}
\ref{fg-fp-local} is what one needs to prove when showing that a
morphism of schemes being of locally of finite type or locally of
finite presentation is local on the source.
\end{remark}



[^always]:
    This catchy phrasing for the proposition is taken from [Vakil's
    notes][vakil].



[vakil]: //math216.wordpress.com/